# Generated by Django 4.1.7 on 2023-03-03 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0006_alter_advertisement_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favouriteadv',
            old_name='user',
            new_name='user_id',
        ),
    ]
