# Generated by Django 4.1.7 on 2023-03-04 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0008_rename_user_id_favouriteadv_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favouriteadv',
            old_name='creator',
            new_name='user',
        ),
    ]
