# Generated by Django 4.1.7 on 2023-03-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0010_alter_favouriteadv_fav_adv'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='draft',
            field=models.BooleanField(default=True),
        ),
    ]
