# Generated by Django 4.1.7 on 2023-03-05 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0011_advertisement_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouriteadv',
            name='fav_adv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adv', to='advertisements.advertisement', verbose_name='обявление'),
        ),
    ]
