# Generated by Django 4.1.6 on 2023-02-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_tags_options_remove_article_tags_relationship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=70, verbose_name='Тэг'),
        ),
    ]
