# Generated by Django 4.1.6 on 2023-02-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_rename_tag_article_scopes_relationship_is_main'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Relationship',
            new_name='Scope',
        ),
        migrations.RemoveField(
            model_name='article',
            name='scopes',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(through='articles.Scope', to='articles.tags'),
        ),
    ]
